### PR TITLE
Dockerize Local Install

### PR DESCRIPTION
**Pull request by kojiromike**
This PR enables people with Docker running on their systems to get asciiflow running locally by executing one command: `make`.

If you merge this PR, you can also get Docker themselves to make a trusted build of this image, so people who want to can run asciiflow
without pulling the repo at all -- they could just do `docker run -dP lewish/asciiflow2`

### CODE REVIEW

**Comment by kojiromike** [comment]
bump?

**Comment by immanuelfodor** [comment]
This PR works fine, thanks!

**Comment by Qix-** [comment]
I will address this differently in AF3, but thanks for the PR!

**Comment by crazybber** [comment]
i think repo should merge this PR,which user can use now, AF3 still can power it.

**Comment by 0xN0x** [comment]
Can it be merged ? @Qix- @lewish 
It was closed because it will be in AF3, however more than 2 years later AF3 is still not released.
It would be interesting to have it while waiting, and it can be refactored once AF3 is released if it's still an ongoing project.

**Pull request closed without merging**
